import Chat from "@/components/Chat";
import { RootState } from "@/redux/store";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { useSelector } from "react-redux";

const chat = () => {
  const router = useRouter();
  const isAuth = useSelector((state: RootState) => state.auth.isAuth)!;

  useEffect(() => {
    if (!isAuth) {
      router.push("/");
    }
  }, [isAuth]);

  return (
    <>
      <Head>
        <title>Chat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Chat />
    </>
  );
};
export default chat;
